### ISSUE TITLE
Modern::Perl is a additional dependency

### ISSUE THREAD

**Issue by omena89** [tschaefer/linux-iwd#1]
hi.
my system needs after the install the modern::perl module. please add to the dependency list.

**Comment by tschaefer** [comment]
Hi,

Actually I forgot to remove the usage of `Modern::Perl` in one file. This is fixed in https://github.com/tschaefer/linux-iwd/commit/000e6847f4b7ddf6a78c9707a40b8a7f48eb53a2. So no further dependency needed anymore.

Thx.
